
# This file is automatically generated, you probably don't want to edit this

multipleresponseOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multipleresponseOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            resps = NULL,
            endorsed = 1,
            order = "decreasing",
            showTotal = TRUE,
            showCounts = TRUE,
            showResponses = TRUE,
            showCases = TRUE,
            yaxis = "cases",
            plotWidth = 400,
            plotHeight = 300, ...) {

            super$initialize(
                package="MultipleResponse",
                name="multipleresponse",
                requiresData=TRUE,
                ...)

            private$..resps <- jmvcore::OptionVariables$new(
                "resps",
                resps,
                required=TRUE,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..endorsed <- jmvcore::OptionInteger$new(
                "endorsed",
                endorsed,
                default=1)
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "decreasing",
                    "increasing",
                    "none"),
                default="decreasing")
            private$..showTotal <- jmvcore::OptionBool$new(
                "showTotal",
                showTotal,
                default=TRUE)
            private$..showCounts <- jmvcore::OptionBool$new(
                "showCounts",
                showCounts,
                default=TRUE)
            private$..showResponses <- jmvcore::OptionBool$new(
                "showResponses",
                showResponses,
                default=TRUE)
            private$..showCases <- jmvcore::OptionBool$new(
                "showCases",
                showCases,
                default=TRUE)
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "counts",
                    "responses",
                    "cases"),
                default="cases")
            private$..plotWidth <- jmvcore::OptionInteger$new(
                "plotWidth",
                plotWidth,
                default=400)
            private$..plotHeight <- jmvcore::OptionInteger$new(
                "plotHeight",
                plotHeight,
                default=300)

            self$.addOption(private$..resps)
            self$.addOption(private$..endorsed)
            self$.addOption(private$..order)
            self$.addOption(private$..showTotal)
            self$.addOption(private$..showCounts)
            self$.addOption(private$..showResponses)
            self$.addOption(private$..showCases)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
        }),
    active = list(
        resps = function() private$..resps$value,
        endorsed = function() private$..endorsed$value,
        order = function() private$..order$value,
        showTotal = function() private$..showTotal$value,
        showCounts = function() private$..showCounts$value,
        showResponses = function() private$..showResponses$value,
        showCases = function() private$..showCases$value,
        yaxis = function() private$..yaxis$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value),
    private = list(
        ..resps = NA,
        ..endorsed = NA,
        ..order = NA,
        ..showTotal = NA,
        ..showCounts = NA,
        ..showResponses = NA,
        ..showCases = NA,
        ..yaxis = NA,
        ..plotWidth = NA,
        ..plotHeight = NA)
)

multipleresponseResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multipleresponseResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        responses = function() private$.items[["responses"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multiple Response")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Multiple Response"))
            self$add(jmvcore::Table$new(
                options=options,
                name="responses",
                title="Frequencies",
                rows="(resps)",
                notes=list(
                    `noc`=""),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Options", 
                        `type`="text"),
                    list(
                        `name`="freq", 
                        `title`="Counts", 
                        `type`="integer", 
                        `visible`="(showCounts)"),
                    list(
                        `name`="responsepercent", 
                        `title`="% of Responses", 
                        `type`="number", 
                        `format`="pc", 
                        `visible`="(showResponses)"),
                    list(
                        `name`="casepercent", 
                        `title`="% of Cases", 
                        `type`="number", 
                        `format`="pc", 
                        `visible`="(showCases)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Frequency Plot",
                width=400,
                height=300,
                renderFun=".plot"))}))

multipleresponseBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multipleresponseBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MultipleResponse",
                name = "multipleresponse",
                version = c(1,0,0),
                options = options,
                results = multipleresponseResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Multiple Response
#'
#' 
#' @param data .
#' @param resps .
#' @param endorsed .
#' @param order .
#' @param showTotal .
#' @param showCounts .
#' @param showResponses .
#' @param showCases .
#' @param yaxis .
#' @param plotWidth .
#' @param plotHeight .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$responses} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$responses$asDF}
#'
#' \code{as.data.frame(results$responses)}
#'
#' @export
multipleresponse <- function(
    data,
    resps,
    endorsed = 1,
    order = "decreasing",
    showTotal = TRUE,
    showCounts = TRUE,
    showResponses = TRUE,
    showCases = TRUE,
    yaxis = "cases",
    plotWidth = 400,
    plotHeight = 300) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("multipleresponse requires jmvcore to be installed (restart may be required)")

    if ( ! missing(resps)) resps <- jmvcore::resolveQuo(jmvcore::enquo(resps))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(resps), resps, NULL))

    for (v in resps) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- multipleresponseOptions$new(
        resps = resps,
        endorsed = endorsed,
        order = order,
        showTotal = showTotal,
        showCounts = showCounts,
        showResponses = showResponses,
        showCases = showCases,
        yaxis = yaxis,
        plotWidth = plotWidth,
        plotHeight = plotHeight)

    analysis <- multipleresponseClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

