
# This file is automatically generated, you probably don't want to edit this

crosstabsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "crosstabsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            resps = NULL,
            group = NULL,
            endorsed = 1,
            order = "decreasing",
            computedValues = "count", ...) {

            super$initialize(
                package="vijMR",
                name="crosstabs",
                requiresData=TRUE,
                ...)

            private$..resps <- jmvcore::OptionVariables$new(
                "resps",
                resps,
                required=TRUE,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..endorsed <- jmvcore::OptionInteger$new(
                "endorsed",
                endorsed,
                default=1)
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "decreasing",
                    "increasing",
                    "none"),
                default="decreasing")
            private$..computedValues <- jmvcore::OptionList$new(
                "computedValues",
                computedValues,
                options=list(
                    "count",
                    "responses",
                    "cases",
                    "options"),
                default="count")

            self$.addOption(private$..resps)
            self$.addOption(private$..group)
            self$.addOption(private$..endorsed)
            self$.addOption(private$..order)
            self$.addOption(private$..computedValues)
        }),
    active = list(
        resps = function() private$..resps$value,
        group = function() private$..group$value,
        endorsed = function() private$..endorsed$value,
        order = function() private$..order$value,
        computedValues = function() private$..computedValues$value),
    private = list(
        ..resps = NA,
        ..group = NA,
        ..endorsed = NA,
        ..order = NA,
        ..computedValues = NA)
)

crosstabsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "crosstabsResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        crosstab = function() private$.items[["crosstab"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mutible Response Crosstab")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="MR Crosstabs Text"))
            self$add(jmvcore::Table$new(
                options=options,
                name="crosstab",
                title="Crosstab",
                rows="(resps)",
                notes=list(
                    `noc`=""),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Options", 
                        `type`="text")),
                clearWith=list(
                    "resps",
                    "endorsed",
                    "order")))}))

crosstabsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "crosstabsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijMR",
                name = "crosstabs",
                version = c(1,0,0),
                options = options,
                results = crosstabsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Multiple Response Crosstabs
#'
#' 
#' @param data .
#' @param resps .
#' @param group .
#' @param endorsed .
#' @param order .
#' @param computedValues .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$crosstab} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$crosstab$asDF}
#'
#' \code{as.data.frame(results$crosstab)}
#'
#' @export
crosstabs <- function(
    data,
    resps,
    group,
    endorsed = 1,
    order = "decreasing",
    computedValues = "count") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("crosstabs requires jmvcore to be installed (restart may be required)")

    if ( ! missing(resps)) resps <- jmvcore::resolveQuo(jmvcore::enquo(resps))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(resps), resps, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in resps) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- crosstabsOptions$new(
        resps = resps,
        group = group,
        endorsed = endorsed,
        order = order,
        computedValues = computedValues)

    analysis <- crosstabsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

