
# This file is automatically generated, you probably don't want to edit this

frequenciesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "frequenciesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            resps = NULL,
            endorsed = 1,
            optionname = "Options",
            order = "decreasing",
            showTotal = TRUE,
            showCounts = TRUE,
            showResponses = TRUE,
            showCases = TRUE,
            yaxis = "cases",
            size = "medium", ...) {

            super$initialize(
                package="vijMR",
                name="frequencies",
                requiresData=TRUE,
                ...)

            private$..resps <- jmvcore::OptionVariables$new(
                "resps",
                resps,
                required=TRUE,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..endorsed <- jmvcore::OptionInteger$new(
                "endorsed",
                endorsed,
                default=1)
            private$..optionname <- jmvcore::OptionString$new(
                "optionname",
                optionname,
                default="Options")
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "decreasing",
                    "increasing",
                    "none"),
                default="decreasing")
            private$..showTotal <- jmvcore::OptionBool$new(
                "showTotal",
                showTotal,
                default=TRUE)
            private$..showCounts <- jmvcore::OptionBool$new(
                "showCounts",
                showCounts,
                default=TRUE)
            private$..showResponses <- jmvcore::OptionBool$new(
                "showResponses",
                showResponses,
                default=TRUE)
            private$..showCases <- jmvcore::OptionBool$new(
                "showCases",
                showCases,
                default=TRUE)
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "counts",
                    "responses",
                    "cases"),
                default="cases")
            private$..size <- jmvcore::OptionList$new(
                "size",
                size,
                options=list(
                    "small",
                    "medium",
                    "large",
                    "huge"),
                default="medium")

            self$.addOption(private$..resps)
            self$.addOption(private$..endorsed)
            self$.addOption(private$..optionname)
            self$.addOption(private$..order)
            self$.addOption(private$..showTotal)
            self$.addOption(private$..showCounts)
            self$.addOption(private$..showResponses)
            self$.addOption(private$..showCases)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..size)
        }),
    active = list(
        resps = function() private$..resps$value,
        endorsed = function() private$..endorsed$value,
        optionname = function() private$..optionname$value,
        order = function() private$..order$value,
        showTotal = function() private$..showTotal$value,
        showCounts = function() private$..showCounts$value,
        showResponses = function() private$..showResponses$value,
        showCases = function() private$..showCases$value,
        yaxis = function() private$..yaxis$value,
        size = function() private$..size$value),
    private = list(
        ..resps = NA,
        ..endorsed = NA,
        ..optionname = NA,
        ..order = NA,
        ..showTotal = NA,
        ..showCounts = NA,
        ..showResponses = NA,
        ..showCases = NA,
        ..yaxis = NA,
        ..size = NA)
)

frequenciesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "frequenciesResults",
    inherit = jmvcore::Group,
    active = list(
        responses = function() private$.items[["responses"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multiple Response Frequencies")
            self$add(jmvcore::Table$new(
                options=options,
                name="responses",
                title="Frequencies",
                rows="(resps)",
                notes=list(
                    `noc`=""),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Options", 
                        `type`="text"),
                    list(
                        `name`="freq", 
                        `title`="Counts", 
                        `type`="integer", 
                        `visible`="(showCounts)"),
                    list(
                        `name`="responsepercent", 
                        `title`="% of Responses", 
                        `type`="number", 
                        `format`="pc", 
                        `visible`="(showResponses)"),
                    list(
                        `name`="casepercent", 
                        `title`="% of Cases", 
                        `type`="number", 
                        `format`="pc", 
                        `visible`="(showCases)")),
                clearWith=list(
                    "resps",
                    "endorsed",
                    "order")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Frequency Plot",
                width=400,
                height=300,
                renderFun=".plot",
                clearWith=list(
                    "resps",
                    "endorsed",
                    "order",
                    "yaxis",
                    "size")))}))

frequenciesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "frequenciesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijMR",
                name = "frequencies",
                version = c(1,0,0),
                options = options,
                results = frequenciesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Multiple Response Frequencies
#'
#' 
#' @param data .
#' @param resps .
#' @param endorsed .
#' @param optionname .
#' @param order .
#' @param showTotal .
#' @param showCounts .
#' @param showResponses .
#' @param showCases .
#' @param yaxis .
#' @param size .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$responses} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$responses$asDF}
#'
#' \code{as.data.frame(results$responses)}
#'
#' @export
frequencies <- function(
    data,
    resps,
    endorsed = 1,
    optionname = "Options",
    order = "decreasing",
    showTotal = TRUE,
    showCounts = TRUE,
    showResponses = TRUE,
    showCases = TRUE,
    yaxis = "cases",
    size = "medium") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("frequencies requires jmvcore to be installed (restart may be required)")

    if ( ! missing(resps)) resps <- jmvcore::resolveQuo(jmvcore::enquo(resps))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(resps), resps, NULL))

    for (v in resps) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- frequenciesOptions$new(
        resps = resps,
        endorsed = endorsed,
        optionname = optionname,
        order = order,
        showTotal = showTotal,
        showCounts = showCounts,
        showResponses = showResponses,
        showCases = showCases,
        yaxis = yaxis,
        size = size)

    analysis <- frequenciesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

